// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMT5CBZ4q_QK9qh-7Pa3XMogCN5TwuXJY',
    appId: '1:851715261172:web:3e48bd80121c073ec354a1',
    messagingSenderId: '851715261172',
    projectId: 'shopapp3-9dfa3',
    authDomain: 'shopapp3-9dfa3.firebaseapp.com',
    storageBucket: 'shopapp3-9dfa3.appspot.com',
    measurementId: 'G-1Q946BHV2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmPuPJqRa8AT77LrWRYDdabwc3B9ekgu0',
    appId: '1:851715261172:android:ecd1ae2441d66503c354a1',
    messagingSenderId: '851715261172',
    projectId: 'shopapp3-9dfa3',
    storageBucket: 'shopapp3-9dfa3.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMT5CBZ4q_QK9qh-7Pa3XMogCN5TwuXJY',
    appId: '1:851715261172:web:7c19eed95ae5ec92c354a1',
    messagingSenderId: '851715261172',
    projectId: 'shopapp3-9dfa3',
    authDomain: 'shopapp3-9dfa3.firebaseapp.com',
    storageBucket: 'shopapp3-9dfa3.appspot.com',
    measurementId: 'G-HBLERFKCT8',
  );
}
